### ISSUE TITLE
Access to precomputed memorization scores?

### ISSUE THREAD

**Issue by shoaibahmed** [xszheng2020/memorization#1]
Hey. Thanks for releasing your code. 
Do you also have any plans for releasing the memorization scores that you computed? Just wondering if we have to recompute them for evaluation purposes. I don't see them being available right now (maybe they are already there, but I missed them).
Thanks!

**Comment by xszheng2020** [comment]
Hi, @shoaibahmed, thanks for your interest in our work. 
The memorization scores for every dataset have been released. 
For example, for CIFAR 10, they are in "memorization/cifar/saved/score_42/"

**Comment by shoaibahmed** [comment]
Great! I can see them now.
Many thanks for your response.
